export const BASE_PATH = "/static/icons";

export const KEYS_FOR_ICONS = {
  ANGULAR: `${BASE_PATH}/angular.webp`,
  ASTRO: `${BASE_PATH}/astro.webp`,
  BITBUCKET: `${BASE_PATH}/bitbucket.webp`,
  CONFLUENCE: `${BASE_PATH}/confluence.webp`,
  CSS: `${BASE_PATH}/css.webp`,
  ELEMENTOR: `${BASE_PATH}/elementor.webp`,
  FLUTTER: `${BASE_PATH}/flutter.webp`,
  GIT: `${BASE_PATH}/git.webp`,
  GITHUB: `${BASE_PATH}/github.webp`,
  HTML: `${BASE_PATH}/html.webp`,
  JENKINS: `${BASE_PATH}/jenkins.webp`,
  JIRA: `${BASE_PATH}/jira.webp`,
  JS: `${BASE_PATH}/js.webp`,
  JAVASCRIPT: `${BASE_PATH}/js.webp`,
  NESTJS: `${BASE_PATH}/nestjs.webp`,
  NODEJS: `${BASE_PATH}/nodejs.webp`,
  PM2: `${BASE_PATH}/pm2.webp`,
  POSTGRESQL: `${BASE_PATH}/postgresql.webp`,
  REACT: `${BASE_PATH}/react.webp`,
  SCRUM: `${BASE_PATH}/scrum.webp`,
  TAILWIND: `${BASE_PATH}/tailwind.webp`,
  TYPESCRIPT: `${BASE_PATH}/typescript.webp`,
  WORDPRESS: `${BASE_PATH}/wordpress.webp`,
  CPP: `${BASE_PATH}/cpp.webp`,
  JAVA: `${BASE_PATH}/java.webp`,
  MYSQL: `${BASE_PATH}/mysql.webp`,
  PHP: `${BASE_PATH}/php.webp`,
  FIGMA: `${BASE_PATH}/figma.webp`,
  NEXTJS: `${BASE_PATH}/nextjs.webp`,
  OPENAI: `${BASE_PATH}/openai.webp`,
};
